version: 2.1

jobs:
  test:
    docker:
      - image: cypress/browsers:node-18.12.0-chrome-107
    steps:
      - checkout
      - run: npm ci
      - run: docker-compose up -d --build
      - run: npx wait-on http://localhost:3000
      - run: npx cypress run
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  run-tests:
    jobs:
      - test