executors:
  cypress-executor:
    docker:
      - image: cypress/browsers:node-18.12.0-chrome-107
    working_directory: ~/project

jobs:
  test:
    executor: cypress-executor
    steps:
      - checkout

      - run:
          name: Install deps
          command: npm ci

      - run:
          name: Start docker-compose
          command: docker-compose up -d --build

      - run:
          name: Wait for frontend
          command: npx wait-on http://localhost:3000

      - run:
          name: Run Cypress
          command: npx cypress run

      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots

      - store_artifacts:
          path: cypress/videos
          destination: videos

workflows:
  run-tests:
    jobs:
      - test
