version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: npm install
      - run: docker compose up -d --build
      - run: npx wait-on http://localhost:3000
      - run: npx cypress run
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  run-tests:
    jobs:
      - test